version: '3'

services:
  motion:
    image: granthouston44/motion:motionrpi  # Replace with your actual Motion Docker image
    ports:
      - "8081:8081"
  nginx:
    image: granthouston44/nginx:revproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/domain:/mnt/letsencrypt/  # Mounting the SSL certificates
    restart: unless-stopped
