version: '3'

services:
  motion:
    image: granthouston44/motion:motionrpi  # Replace with your actual Motion Docker image
    ports:
      - "8081:8081"
    environment:
      NOIP_USERNAME: ${NOIP_USERNAME}
      NOIP_PASSWORD: ${NOIP_PASSWORD}
      MOTION_USERNAME: ${MOTION_USERNAME}
      MOTION_PASSWORD: ${MOTION_PASSWORD}
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  nginx:
    image: granthouston44/nginx:revproxy
    depends_on:
      - motion
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/domain:/mnt/letsencrypt/ # Mounting the SSL certificates
      - /host/path/nginx.conf:/etc/nginx/nginx.conf:ro  
    restart: unless-stopped
