version: '3'

services:
  motion:
    image: granthouston44/motion:motionrpi  # Replace with your actual Motion Docker image
    ports:
      - "8081:8081"
    environment:
      NOIP_USERNAME: ${NOIP_USERNAME}
      NOIP_PASSWORD: ${NOIP_PASSWORD}
      MOTION_USERNAME: ${MOTION_USERNAME}
      MOTION_PASSWORD: ${MOTION_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/0/detection/connection || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m

  nginx:
    build:
      context: ./Dockerfiles/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      motion:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - /etc/letsencrypt:/mnt/letsencrypt
      - /var/www/certbot:/var/www/certbot
    restart: unless-stopped
